// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Users_Ms.Data;

namespace Users_MS.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Users_Ms.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(36);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1dd39bfd-2b28-434e-ae53-be94ed4a32af"),
                            Email = "test1",
                            FirstName = "test1",
                            LastName = "test1",
                            Password = "test1",
                            UserName = "test1"
                        },
                        new
                        {
                            Id = new Guid("9a9cb004-a4d8-4ae2-9178-1433c37cab82"),
                            Email = "test1",
                            FirstName = "test2",
                            LastName = "test1",
                            Password = "test1",
                            UserName = "test1"
                        },
                        new
                        {
                            Id = new Guid("e9276906-5b6c-4ce1-9a53-57e1fc69979c"),
                            Email = "test1",
                            FirstName = "test3",
                            LastName = "test1",
                            Password = "test1",
                            UserName = "test1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
