// <auto-generated />
using System;
using Likes_MS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Likes_MS.Migrations
{
    [DbContext(typeof(LikeContext))]
    [Migration("20200111162341_initia;-migration")]
    partial class initiamigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Likes_MS.Data.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(36);

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(36);

                    b.Property<int>("PersonLike")
                        .HasColumnType("int")
                        .HasMaxLength(2);

                    b.Property<Guid>("PetId")
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(36);

                    b.Property<int>("PetLike")
                        .HasColumnType("int")
                        .HasMaxLength(2);

                    b.Property<Guid>("PetOwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(36);

                    b.HasKey("Id");

                    b.ToTable("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
